### ISSUE TITLE
make:admin:user and BaseAdminUser should support doctrine attributes

### ISSUE THREAD

**Issue by tacman** [acantepie/umbrella#19]
### Umbrella version affected

all

### Description

If a project is using doctrine attributes (rather than annotations), generating the admin user should generate attributes and not annotations.

### How to reproduce

Configure doctrine for attributes

```yaml
# config/packages/doctrine.yaml

doctrine:
  orm:
    mappings:
      App:
        type: attribute
```

make the admin user class and clear the cache

    php bin/console make:admin:user
    php bin/console cache:clear
 
The error is

```
Class "App\Entity\AdminUser" sub class of "Umbrella\AdminBundle\Entity\BaseAdminUser" is not a valid entity or mapped super class.  
```

The BaseAdminUser needs to support both annotations and attributes, which should be possible:

https://tomasvotruba.com/blog/how-to-refactor-custom-doctrine-annotations-to-attributes/
