### ISSUE TITLE
Cannot get ckeditor config to work

### ISSUE THREAD

**Issue by jeroenmimpen** [acantepie/umbrella#32]
### Umbrella version affected

6.1

### Description

When trying to create a ckeditor config I get an error:

InvalidTypeException
HTTP 500 Internal Server Error
Invalid type for path "umbrella_core.ckeditor.configs.my_custom_config.toolbar". Expected "scalar", but got "array".

![image](https://user-images.githubusercontent.com/10400659/194852465-d454f167-e11d-4333-b609-778c60b9b569.png)

### How to reproduce

I add the following to a config file. This is copy pasted from https://acantepie.github.io/umbrella/#/config/umbrella_core. I also tried various variations but none of them worked.

```
    ckeditor:
        configs:
            # Example:
            my_custom_config: { toolbar: [ { name: clipboard, items: [ Undo, Redo ] } ], uiColor: '#FEFEFE' }

            # Prototype
            name: [ ]
```
